# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext-graybuck2019-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0.0
  - macs2=2.1.2
  - fastqc=0.11.8
  - star=2.5.3
  - picard=2.18.27
  - rseqc=2.6.2
  - samtools=1.3
  - bowtie=1.1.1
  - trimmomatic=0.39
  - igvtools=2.5.3
  - bedtools=2.29.2
  - fastx_toolkit=0.0.14
  - ucsc-wigToBigWig=366
  - trim-galore=0.6.2
  - homer=4.11.0
